name: pr-11421-all-demos
type: gradio-space
sdk: gradio

metadata:
  space_id: Chris4K/pr-11421-all-demos
  original_url: https://huggingface.co/spaces/Chris4K/pr-11421-all-demos

deploy:
  targets:
    - public-repo
    - huggingface

build:
  command: bash build.sh

test:
  command: echo "Tests not yet implemented"
